Handle failures

diff --git a/bin/get-results b/bin/get-results
--- a/bin/get-results
+++ b/bin/get-results
@@ -5,8 +5,23 @@ declare -r MY_D="$(readlink -f "$(dirname "${BASH_SOURCE}")")"
 
 mkdir -p "$(dirname "${RESULTS_TSV}")" \
   || die "Failed to make dir for '${RESULTS_TSV}'"
+if failed; then
+  mkdir -p "$(dirname "${STATUS_YAML}")" \
+    || die "Failed to make dir for '${STATUS_YAML}'"
+  started \
+    && run_kubectl get "jobs/${K8S_JOB_NAME}" -o yaml > "${STATUS_YAML}"
+  run_kubectl describe "jobs/${K8S_JOB_NAME}" > "${JOB_RESULTS_D}/${JOB_NAME}.describe.txt" || true
+  run_kubectl get pods -l "${K8S_RUNNER_LABELS}" -o yaml > "${JOB_RESULTS_D}/${JOB_NAME}.pods.yaml" || true
+  for pod in $(run_kubectl get pods -l "${K8S_RUNNER_LABELS}" -o name 2>/dev/null); do
+    pod_name="${pod#pod/}"
+    run_kubectl logs "${pod}" > "${JOB_RESULTS_D}/${pod_name}.log" || true
+    run_kubectl describe "${pod}" > "${JOB_RESULTS_D}/${pod_name}.describe.txt" || true
+  done
+  exit "${EXIT_FAILED}"
+fi
+
 if force || [[ ! -f "${RESULTS_TSV}" ]]; then
-  complete || die "Job isn't complete yet (or hasn't been started)"
+  complete || die "Job isn't complete yet, failed, or hasn't been started"
   (DEBUG=t; run_kubectl \
     exec "${RELEASE}-target-0" -- head -n1 "/results/results.tsv.0") \
     > "${RESULTS_TSV}"
diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -4,13 +4,16 @@ declare -r MY_D="$(readlink -f "$(dirname "${BASH_SOURCE}")")"
 . "${MY_D}/include.sh"
 
 declare CMD="upgrade --install"
+declare -r DEBUG_RUNNER_POD="${DEBUG_RUNNER_POD:-}"
 
-DEBUG_FLAG=""
+DEBUG_FLAGS=""
 OVERWRITE="${OVERWRITE:-}"
 if debug; then
   CMD="template"
-  DEBUG_FLAG="--debug"
+  DEBUG_FLAGS="--debug"
 fi
+[[ -n "${DEBUG_RUNNER_POD}" && "$(echo "${DEBUG_RUNNER_POD}" | tr 'a-z' 'A-Z')" != "FALSE" ]] \
+  && DEBUG_FLAGS="${DEBUG_FLAGS} --set debug_runner_pod=true"
 
 if ! force; then 
   if have_saved_results; then
@@ -33,7 +36,8 @@ if ! force; then
   fi
   debug && msg "not running or complete, checking if failed..."
   if failed; then
-    msg "Job failed. Run with envvar FORCE=true to run it again."
+    msg "Job failed. Run with envvar FORCE=true to run it again. Saving status..."
+    "${ROOT_D}/bin/get-results" "${@}"
     exit "${EXIT_FAILED}"
   fi
 else
@@ -55,12 +59,14 @@ K8S_SA="${RELEASE}" \
 if [[ -e "${RESULTS_TSV}" || -e "${STATUS_YAML}" ]]; then
   msg "Archiving old results"
   arc_ts="$(date +%s)"
-  [[ -e "${RESULTS_TSV}" ]] \
-    && (set -x; mv "${RESULTS_TSV}" "${RESULTS_TSV}.archived_at_${arc_ts}") \
-    || die "Failed to archive old results"
-  [[ -e "${STATUS_YAML}" ]] \
-    && (set -x; mv "${STATUS_YAML}" "${STATUS_YAML}.archived_at_${arc_ts}") \
-    || die "Failed to archive old results"
+  if [[ -e "${RESULTS_TSV}" ]]; then
+    (set -x; mv "${RESULTS_TSV}" "${RESULTS_TSV}.archived_at_${arc_ts}") \
+      || die "Failed to archive old results"
+  fi
+  if [[ -e "${STATUS_YAML}" ]]; then
+    (set -x; mv "${STATUS_YAML}" "${STATUS_YAML}.archived_at_${arc_ts}") \
+      || die "Failed to archive old results"
+  fi
 fi
 
 if started; then
@@ -83,7 +89,7 @@ msg "Installing chart"
   --set tbot.token="${TOKEN}" \
   -f "${JOB_YAML}" \
   -f "${CLUSTER_YAML}" \
-  ${DEBUG_FLAG}
+  ${DEBUG_FLAGS} \
   ) \
   || die "Failed to helm"
 
diff --git a/bin/run-cases b/bin/run-cases
--- a/bin/run-cases
+++ b/bin/run-cases
@@ -50,7 +50,7 @@ for config_file in "${CONFIG_D}/${cluster_name}".*; do
         ;;
       125)
         # failed
-        if [[ -n "${STOP_ON_FAILURE}" && "${STOP_ON_FAILURE^^}" != "FALSE" ]]; then
+        if [[ -n "${STOP_ON_FAILURE}" && "$(echo "${STOP_ON_FAILURE}" | tr 'a-z' 'A-Z')" != "FALSE" ]]; then
           echo >&2 "test case '${config_file}' failed and STOP_ON_FAILURE set, exiting..."
           exit "${ret}"
         fi
@@ -58,8 +58,13 @@ for config_file in "${CONFIG_D}/${cluster_name}".*; do
         break
         ;;
       124)
-        # die / unexpected hard failure
-        exit "${ret}"
+        # die / hard failure
+        if [[ -n "${STOP_ON_FAILURE}" && "$(echo "${STOP_ON_FAILURE}" | tr 'a-z' 'A-Z')" != "FALSE" ]]; then
+          echo >&2 "test case '${config_file}' hit hard failure and STOP_ON_FAILURE set, exiting..."
+          exit "${ret}"
+        fi
+        cleanup "${config_file}"
+        break
         ;;
       *)
         printf >&2 "Unknown exit code from bin/run for '%s': %s\n" "${config_file#${ROOT_D}/}" "${ret}"
diff --git a/files/race-kubectl b/files/race-kubectl
--- a/files/race-kubectl
+++ b/files/race-kubectl
@@ -1,13 +1,23 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-# Uncomment to debug pod before run
-#trap 'exit 0' TERM INT
-#while true; do
-#  sleep 10 &
-#  wait $!
-#  echo 'Waiting for you to debugtest-runner'
-#done
+declare -r DEBUG="${DEBUG:-}"
+debug() {
+  [[ -n "${DEBUG}" && "$(echo "${DEBUG}" | tr 'a-z' 'A-Z')" != "FALSE" ]]
+}
+on_fail() {
+  ret="$?"
+  printf >&2 "race-kubectl failed with exit %s\n" "${ret}"
+  while true; do
+    sleep 10 &
+    wait $!
+    echo 'Waiting for you to debugtest-runner'
+  done
+}
+if debug; then
+  set -Ex
+  trap on_fail ERR
+fi
 
 # Mark start in the logs
 date >&2
@@ -18,6 +28,7 @@ msg() {
 
 die() {
   msg "ERROR: ${*}"
+  debug && on_fail
   exit 1
 }
 
@@ -58,6 +69,32 @@ declare -r TARGET_PREFIX="${TARGET_PREFIX:-}"
 [[ -n "${TARGET_PREFIX}" ]] \
   || die "TARGET_PREFIX not set. Set it to the name of the remote StatefulSet we're running on."
 declare -r TARGET_POD="${TARGET_PREFIX}-${ORDINAL}"
+
+wait_for_pod() {
+  local pod="${1}"
+  local max="${2:-5000}"
+  [[ -z "${pod}" ]] && {
+    echo >&2 "Pod empty in wait_for_pod"
+    exit 1;
+  }
+  until (set -x; kubectl get "pod/${pod}") || [[ "${max}" -le 0 ]]; do
+    printf >&2 "Waiting for target pod '%s' to exist...%d\n" "${pod}" "${max}"
+    sleep 1
+    max="$(( max - 1 ))"
+  done
+}
+export -f wait_for_pod # Because timeout won't work with functions
+# We use if+case because we've set -e -- timeout failure would cause exit
+if timeout "${MAX_READY_WAIT}" bash -c "wait_for_pod '${TARGET_POD}'"; then
+  msg "Pod '${TARGET_POD}' exists, waiting for it to be ready..."
+else
+  ret="${?}"
+  case "${ret}" in
+    124) die "Timed out waiting for pod '${TARGET_POD}' to exist" ;;
+    0) die "This should be unreachable code" ;;
+    *) die "Unknown failure waiting for target pod '${TARGET_POD}' to exist." ;;
+  esac
+fi
 
 declare -r OUT_POD_NO_TP="${OUT_POD_NO_TP:-/dev/shm/${TARGET_POD}.no-teleport.yaml}"
 kubectl get "pod/${TARGET_POD}" -o yaml \
@@ -103,6 +140,8 @@ kubectl wait \
   --timeout="${MAX_READY_WAIT}" \
   || die "Target pod '${TARGET_POD}' was not ready after '${MAX_READY_WAIT}'"
 msg "Seeing permission errors about 'wait' above? Add perms, but things are still working. kubectl falls back to polling if it doesn't have wait perms."
+
+sleep 1 # Because sometimes it takes a sec even after the pod is "ready"
 
 printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
   "task" \
